-- Migration 056: Permission catalog table seeded from allowedPermissions.

CREATE TABLE IF NOT EXISTS permissions (
    key text PRIMARY KEY,
    resource text NOT NULL,
    verb text NOT NULL,
    description text NOT NULL DEFAULT '',
    system bool NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO permissions (key, resource, verb, description, system) VALUES
('*', '*', '*', 'Wildcard permission allowing full access', true),
('events:write', 'events', 'write', 'Write tracking events', true),
('profiles:read', 'profiles', 'read', 'Read customer profiles', true),
('schemas:read', 'schemas', 'read', 'Read event schemas', true),
('schemas:write', 'schemas', 'write', 'Write event schemas', true),
('api_keys:read', 'api_keys', 'read', 'Read API keys', true),
('api_keys:write', 'api_keys', 'write', 'Manage API keys', true),
('privacy:write', 'privacy', 'write', 'Execute privacy and compliance operations', true),
('operations:read', 'operations', 'read', 'Read system operations and status', true),
('operations:write', 'operations', 'write', 'Manage system operations', true),
('users:read', 'users', 'read', 'Read users', true),
('users:write', 'users', 'write', 'Manage users', true),
('roles:read', 'roles', 'read', 'Read RBAC roles', true),
('roles:write', 'roles', 'write', 'Manage RBAC roles', true),
('segments:read', 'segments', 'read', 'Read audience segments', true),
('segments:write', 'segments', 'write', 'Manage audience segments', true),
('templates:read', 'templates', 'read', 'Read message templates', true),
('templates:write', 'templates', 'write', 'Manage message templates', true),
('campaigns:read', 'campaigns', 'read', 'Read marketing campaigns', true),
('campaigns:write', 'campaigns', 'write', 'Manage marketing campaigns', true),
('suppressions:read', 'suppressions', 'read', 'Read suppression lists', true),
('suppressions:write', 'suppressions', 'write', 'Manage suppression lists', true),
('journeys:read', 'journeys', 'read', 'Read journey workflows', true),
('journeys:write', 'journeys', 'write', 'Manage journey workflows', true),
('journeys:publish', 'journeys', 'publish', 'Publish journey workflows', true),
('experiments:read', 'experiments', 'read', 'Read A/B experiments', true),
('experiments:write', 'experiments', 'write', 'Manage A/B experiments', true),
('reports:read', 'reports', 'read', 'Read analytics reports', true),
('reports:write', 'reports', 'write', 'Manage analytics reports', true),
('device_tokens:read', 'device_tokens', 'read', 'Read push notification device tokens', true),
('device_tokens:write', 'device_tokens', 'write', 'Manage device tokens', true),
('ai:read', 'ai', 'read', 'Read AI configurations and models', true),
('ai:configure', 'ai', 'configure', 'Configure AI gateways and providers', true),
('ai:invoke', 'ai', 'invoke', 'Invoke AI models and agents', true),
('prompts:read', 'prompts', 'read', 'Read managed AI prompts', true),
('prompts:write', 'prompts', 'write', 'Manage AI prompt templates', true),
('scoring:read', 'scoring', 'read', 'Read lead scoring rules', true),
('scoring:write', 'scoring', 'write', 'Manage lead scoring rules', true),
('scoring:compute', 'scoring', 'compute', 'Trigger lead score recalculation', true),
('forms:read', 'forms', 'read', 'Read capture forms', true),
('forms:write', 'forms', 'write', 'Manage capture forms', true),
('forms:publish', 'forms', 'publish', 'Publish capture forms', true),
('pages:read', 'pages', 'read', 'Read landing pages', true),
('pages:write', 'pages', 'write', 'Manage landing pages', true),
('pages:publish', 'pages', 'publish', 'Publish landing pages', true),
('assets:read', 'assets', 'read', 'Read media assets', true),
('assets:write', 'assets', 'write', 'Manage media assets', true),
('links:read', 'links', 'read', 'Read trackable links', true),
('links:write', 'links', 'write', 'Manage trackable links', true),
('companies:read', 'companies', 'read', 'Read target companies', true),
('companies:write', 'companies', 'write', 'Manage target companies', true),
('stages:read', 'stages', 'read', 'Read lifecycle stages', true),
('stages:write', 'stages', 'write', 'Manage lifecycle stages', true),
('imports:read', 'imports', 'read', 'Read bulk import jobs', true),
('imports:write', 'imports', 'write', 'Manage bulk import jobs', true),
('extensions:read', 'extensions', 'read', 'Read installed extensions', true),
('extensions:write', 'extensions', 'write', 'Manage extensions', true),
('extensions:install', 'extensions', 'install', 'Install system extensions', true),
('connectors:read', 'connectors', 'read', 'Read data connectors', true),
('connectors:write', 'connectors', 'write', 'Manage data connectors', true),
('connectors:run', 'connectors', 'run', 'Execute data connectors', true),
('messages:read', 'messages', 'read', 'Read sent and queued messages', true),
('messages:write', 'messages', 'write', 'Manage message delivery', true),
('flags:read', 'flags', 'read', 'Read feature flags', true),
('flags:write', 'flags', 'write', 'Manage feature flags', true),
('catalogs:read', 'catalogs', 'read', 'Read reference catalogs', true),
('catalogs:write', 'catalogs', 'write', 'Manage reference catalogs', true)
ON CONFLICT (key) DO NOTHING;
