import { FormEvent, useEffect, useState } from "react";
import { ConnectorPipeline, ConnectorRun, createConnectorPipeline, identifyIdentity, listConnectorPipelines, listConnectorRuns, mergeIdentity, publishConnectorPipeline, unmergeIdentity, updateConnectorPipeline } from "../api";
import { EmptyState, ErrorState } from "../components";
import { message } from "../errors";

const blank = (): Partial<ConnectorPipeline> => ({ name: "", connector_extension_id: "", direction: "source", status: "draft", schedule_enabled: false });

export default function Connectors({ apiKey, baseURL }: { apiKey: string; baseURL: string }) {
  const [items, setItems] = useState<ConnectorPipeline[]>([]); const [selected, setSelected] = useState<ConnectorPipeline | null>(null);
  const [runs, setRuns] = useState<ConnectorRun[]>([]); const [draft, setDraft] = useState<Partial<ConnectorPipeline>>(blank()); const [mapping, setMapping] = useState('{"fields":["external_id"],"idempotency":"upsert"}');
  const [identity, setIdentity] = useState({ external_id: "", namespace: "email", value: "" }); const [merge, setMerge] = useState({ external_id: "", source_external_id: "" }); const [unmerge, setUnmerge] = useState("");
  const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function refresh() { try { const next = await listConnectorPipelines(baseURL, apiKey); setItems(next); if (selected) await select(next.find(x => x.id === selected.id) || selected); } catch (e) { setError(message(e)); } }
  async function select(item: ConnectorPipeline) { setSelected(item); setMapping('{"fields":["external_id"],"idempotency":"upsert"}'); try { setRuns(await listConnectorRuns(baseURL, apiKey, item.id)); } catch (e) { setError(message(e)); } }
  useEffect(() => { if (apiKey) void refresh(); }, [apiKey, baseURL]);
  async function save(e: FormEvent) { e.preventDefault(); try { const item = draft.id ? await updateConnectorPipeline(baseURL, apiKey, draft.id, draft) : await createConnectorPipeline(baseURL, apiKey, draft); setDraft(blank()); setNotice("Pipeline saved."); await refresh(); await select(item); } catch (e) { setError(message(e)); } }
  async function saveSelected(e: FormEvent) { e.preventDefault(); if (!selected) return; try { const item = await updateConnectorPipeline(baseURL, apiKey, selected.id, selected); setSelected(item); setNotice("Pipeline settings saved."); await refresh(); } catch (e) { setError(message(e)); } }
  async function publish() { if (!selected) return; try { await publishConnectorPipeline(baseURL, apiKey, selected.id, JSON.parse(mapping)); setNotice("Mapping frozen as an immutable version."); await refresh(); } catch (e) { setError(message(e)); } }
  async function identify(e: FormEvent) { e.preventDefault(); try { await identifyIdentity(baseURL, apiKey, identity); setNotice("Identity command queued."); } catch (e) { setError(message(e)); } }
  async function mergeProfiles(e: FormEvent) { e.preventDefault(); try { await mergeIdentity(baseURL, apiKey, merge); setNotice("Merge command queued for human review."); } catch (e) { setError(message(e)); } }
  async function restore(e: FormEvent) { e.preventDefault(); try { await unmergeIdentity(baseURL, apiKey, { merge_id: unmerge }); setUnmerge(""); setNotice("Unmerge command queued."); } catch (e) { setError(message(e)); } }
  return <section className="stack connectors-view">
    <article className="card"><div className="eyebrow">Data platform</div><h2>Connectors and pipelines</h2><p className="muted">Sources, sinks, and exports use immutable mappings and the governed event pipeline.</p>{error && <ErrorState title="Failed to load pipelines" description={error} onRetry={() => { setError(""); void refresh(); }} icon="warn" />}{notice && <p className="success" role="status">{notice}</p>}</article>
    <div className="acquisition-grid"><article className="card"><div className="section-title"><h2>Pipelines</h2><button onClick={() => { setSelected(null); setDraft(blank()); }}>New pipeline</button></div>{items.map(item => <button className="resource-row" key={item.id} onClick={() => void select(item)}><strong>{item.name}</strong><span className={`pill ${item.status}`}>{item.status}</span><small>{item.direction} · {item.schedule_enabled ? "scheduled" : "manual"}</small></button>)}{!items.length && <EmptyState title="No pipelines yet" description="Create a new pipeline to sync data across your platforms." icon="plus" cta={{label:"New pipeline",onClick:()=>{setSelected(null);setDraft(blank());}}} />}</article>
      <article className="card">{(draft.name !== undefined && !selected) ? <form className="governance-form" onSubmit={save}><h2>New pipeline</h2><label>Name<input value={draft.name || ""} onChange={e => setDraft({ ...draft, name: e.target.value })} required /></label><label>Connector extension ID<input value={draft.connector_extension_id || ""} onChange={e => setDraft({ ...draft, connector_extension_id: e.target.value })} required /></label><label>Direction<select value={draft.direction} onChange={e => setDraft({ ...draft, direction: e.target.value as ConnectorPipeline["direction"] })}><option value="source">Source</option><option value="sink">Reverse-ETL sink</option><option value="export">Event export</option></select></label><label className="checkbox"><input type="checkbox" checked={!!draft.schedule_enabled} onChange={e => setDraft({ ...draft, schedule_enabled: e.target.checked })} /> Enable schedule</label><button>Create pipeline</button></form> : selected ? <><div className="section-title"><div><div className="eyebrow">{selected.direction}</div><h2>{selected.name}</h2></div><button className="publish-button" onClick={() => void publish()}>Freeze mapping</button></div><form className="governance-form" onSubmit={saveSelected}><label className="checkbox"><input type="checkbox" checked={selected.schedule_enabled} onChange={e => setSelected({ ...selected, schedule_enabled: e.target.checked })} /> Enable schedule</label><label>Interval (seconds)<input type="number" min="1" value={selected.schedule_interval_seconds || 60} onChange={e => setSelected({ ...selected, schedule_interval_seconds: Number(e.target.value) })} /></label><button>Save pipeline settings</button></form><label>Mapping JSON<textarea rows={4} value={mapping} onChange={e => setMapping(e.target.value)} /></label><p className="field-help">Connector: <code>{selected.connector_extension_id}</code></p><h3>Run history</h3>{runs.length ? <table><thead><tr><th>Status</th><th>Rows</th><th>Rejected</th><th>Started</th></tr></thead><tbody>{runs.map(run => <tr key={run.id}><td>{run.status}</td><td>{run.rows_out}/{run.rows_in}</td><td>{run.rows_rejected}</td><td>{new Date(run.started_at).toLocaleString()}</td></tr>)}</tbody></table> : <EmptyState title="No runs yet" description="Pipelines will appear here as they execute." icon="info" />}</> : <EmptyState title="Select a pipeline" description="Choose a pipeline from the list to view details and history." icon="search" />}</article></div>
    <div className="acquisition-grid"><article className="card"><h2>Identify a namespace</h2><form className="single-action" onSubmit={identify}><label>Profile external ID<input value={identity.external_id} onChange={e => setIdentity({ ...identity, external_id: e.target.value })} required /></label><label>Namespace<input value={identity.namespace} onChange={e => setIdentity({ ...identity, namespace: e.target.value })} required /></label><label>Value<input value={identity.value} onChange={e => setIdentity({ ...identity, value: e.target.value })} required /></label><button>Emit identify</button></form></article><article className="card"><h2>Identity merge / unmerge</h2><form className="single-action" onSubmit={mergeProfiles}><label>Winner external ID<input value={merge.external_id} onChange={e => setMerge({ ...merge, external_id: e.target.value })} required /></label><label>Loser external ID<input value={merge.source_external_id} onChange={e => setMerge({ ...merge, source_external_id: e.target.value })} required /></label><button>Emit merge</button></form><form className="single-action" onSubmit={restore}><label>Merge ID<input value={unmerge} onChange={e => setUnmerge(e.target.value)} required /></label><button>Emit unmerge</button></form></article></div>
  </section>;
}
