import { FormEvent, useEffect, useState } from "react";
import { AIActivity, AIBudget, AIProviderConfig, FieldClassification, getAIBudget, listAIActivity, listAIProviders, listFieldClassifications, saveAIProvider, saveFieldClassification } from "../api";

const blankProvider: Partial<AIProviderConfig> = { provider: "fake", status: "active", is_default: true, monthly_budget_cents: 0, endpoint_allowlist: [] };
function message(error: unknown) { return error instanceof Error ? error.message : "Request failed"; }

export default function Governance({ apiKey, baseURL }: { apiKey: string; baseURL: string }) {
  const [providers, setProviders] = useState<AIProviderConfig[]>([]); const [budget, setBudget] = useState<AIBudget | null>(null);
  const [activity, setActivity] = useState<AIActivity[]>([]); const [classifications, setClassifications] = useState<FieldClassification[]>([]);
  const [provider, setProvider] = useState<Partial<AIProviderConfig>>(blankProvider); const [field, setField] = useState<Partial<FieldClassification>>({ entity_type: "profile", classification: "internal", send_to_model: "redact" });
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { try { const [p, b, a, c] = await Promise.all([listAIProviders(baseURL, apiKey), getAIBudget(baseURL, apiKey), listAIActivity(baseURL, apiKey), listFieldClassifications(baseURL, apiKey)]); setProviders(p); setBudget(b); setActivity(a); setClassifications(c); setProvider(p[0] || blankProvider); } catch (e) { setError(message(e)); } }
  useEffect(() => { void load(); }, [apiKey, baseURL]);
  async function saveProvider(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await saveAIProvider(baseURL, apiKey, { ...provider, endpoint_allowlist: (provider.endpoint_allowlist || []).filter(Boolean) }); await load(); } catch (e) { setError(message(e)); } finally { setSaving(false); } }
  async function saveField(e: FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await saveFieldClassification(baseURL, apiKey, field); setField({ entity_type: "profile", classification: "internal", send_to_model: "redact" }); await load(); } catch (e) { setError(message(e)); } finally { setSaving(false); } }
  return <section className="stack governance-view">
    <article className="card"><div className="eyebrow">Provider and budget</div><h2>AI governance settings</h2><p className="muted">Secrets are managed by the server and are never displayed here.</p>
      <form className="governance-form" onSubmit={saveProvider}><label>Provider<select value={provider.provider || "fake"} onChange={e => setProvider({ ...provider, provider: e.target.value as AIProviderConfig["provider"] })}><option value="fake">Fake (development)</option><option value="anthropic">Anthropic</option><option value="openai">OpenAI-compatible</option></select></label><label>Monthly budget (cents)<input type="number" min="0" value={provider.monthly_budget_cents || 0} onChange={e => setProvider({ ...provider, monthly_budget_cents: Number(e.target.value) })} /></label><label className="governance-wide">Endpoint allowlist (one host per line)<textarea value={(provider.endpoint_allowlist || []).join("\n")} onChange={e => setProvider({ ...provider, endpoint_allowlist: e.target.value.split("\n").map(v => v.trim()) })} /></label><button disabled={saving}>{provider.id ? "Save provider" : "Add provider"}</button></form>
      {budget && <p className="field-help">{budget.usage.period}: {budget.usage.cost_cents}¢ used of {budget.monthly_budget_cents || "unlimited"}¢ · {budget.usage.input_tokens + budget.usage.output_tokens} tokens</p>}
    </article>
    <article className="card"><div className="eyebrow">Permission-aware egress</div><h2>Field classifications</h2><form className="governance-form" onSubmit={saveField}><label>Entity<select value={field.entity_type} onChange={e => setField({ ...field, entity_type: e.target.value as FieldClassification["entity_type"] })}><option value="profile">Profile</option><option value="event">Event</option></select></label><label>Field path<input required value={field.field_path || ""} onChange={e => setField({ ...field, field_path: e.target.value })} placeholder="email" /></label><label>Classification<select value={field.classification} onChange={e => setField({ ...field, classification: e.target.value as FieldClassification["classification"] })}><option>public</option><option>internal</option><option>confidential</option><option>restricted</option></select></label><label>Model action<select value={field.send_to_model} onChange={e => setField({ ...field, send_to_model: e.target.value as FieldClassification["send_to_model"] })}><option>redact</option><option>tokenize</option><option>allow</option><option>deny</option></select></label><button disabled={saving}>Add classification</button></form><table><thead><tr><th>Entity</th><th>Field</th><th>Classification</th><th>Model action</th></tr></thead><tbody>{classifications.map(c => <tr key={c.id}><td>{c.entity_type}</td><td>{c.field_path}</td><td>{c.classification}</td><td>{c.send_to_model}</td></tr>)}</tbody></table></article>
    <article className="card"><div className="eyebrow">Append-only audit</div><h2>AI activity</h2><table><thead><tr><th>Action</th><th>Provider/model</th><th>Decision</th><th>Cost</th><th>When</th></tr></thead><tbody>{activity.map(a => <tr key={a.id}><td>{a.action}</td><td>{a.provider}/{a.model}</td><td>{a.policy_decision}</td><td>{a.cost_cents}¢</td><td>{new Date(a.created_at).toLocaleString()}</td></tr>)}</tbody></table></article>
    {error && <p className="error" role="alert">{error}</p>}
  </section>;
}
